### ISSUE TITLE
Cascading Worldgen Lag

### ISSUE THREAD

**Issue by Plisko1** [Olafski/FastLeafDecay#18] opened 2018-10-05 22:39 UTC
I was told that you would be interested in the last 4 lines of this log.  There is a message there, and in other parts of the log that give an error message followed by instructions to report it here.  

> [23:59:56] [Server thread/WARN] [FML]: Fast Leaf Decay loaded a new chunk [-3, -150] in dimension 0 (overworld) while populating chunk [-3, -149], causing cascading worldgen lag.
[23:59:56] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[23:59:56] [Server thread/WARN] [FML]: Fast Leaf Decay loaded a new chunk [-2, -151] in dimension 0 (overworld) while populating chunk [-3, -149], causing cascading worldgen lag.
[23:59:56] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge 

Here is the full log.

https://pastebin.com/T1sG9Uyc

**Comment by Olafski** [comment] 2018-10-05 22:59
This is a duplicate of #12

**Closed by Olafski** 2018-10-05 22:59 UTC
